#!/usr/bin/env bash
set -euo pipefail

show_help() {
  cat <<'HELP'
Usage: tools/operations/deploy_frontend.sh [OPTIONS]

Purpose:
  Generate the static frontend runtime configuration from Terraform outputs,
  deploy frontend/ to the managed S3 bucket, invalidate CloudFront, and verify
  the published site.

Options:
  --terraform-dir DIR    Terraform root directory (default: infra)
  --frontend-dir DIR     Static frontend directory (default: frontend)
  --no-wait              Do not wait for CloudFront invalidation completion
  --skip-http-check      Do not verify the public frontend URL with curl
  -h, --help             Show this help and exit without side effects

Environment variables:
  AWS_PROFILE            Optional AWS CLI profile.

Examples:
  tools/operations/deploy_frontend.sh
  tools/operations/deploy_frontend.sh --no-wait
HELP
}

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
TERRAFORM_DIR="$ROOT_DIR/infra"
FRONTEND_DIR="$ROOT_DIR/frontend"
WAIT_FOR_INVALIDATION=true
HTTP_CHECK=true

while [[ $# -gt 0 ]]; do
  case "$1" in
    --terraform-dir)
      [[ $# -ge 2 ]] || { echo "--terraform-dir requires a value" >&2; exit 2; }
      TERRAFORM_DIR="$2"
      shift 2
      ;;
    --frontend-dir)
      [[ $# -ge 2 ]] || { echo "--frontend-dir requires a value" >&2; exit 2; }
      FRONTEND_DIR="$2"
      shift 2
      ;;
    --no-wait)
      WAIT_FOR_INVALIDATION=false
      shift
      ;;
    --skip-http-check)
      HTTP_CHECK=false
      shift
      ;;
    -h|--help)
      show_help
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      show_help >&2
      exit 2
      ;;
  esac
done

for command in aws jq terraform; do
  command -v "$command" >/dev/null 2>&1 || {
    echo "Required command not found: $command" >&2
    exit 1
  }
done

if [[ "$HTTP_CHECK" == true ]]; then
  command -v curl >/dev/null 2>&1 || {
    echo "Required command not found: curl" >&2
    exit 1
  }
fi

[[ -d "$TERRAFORM_DIR" ]] || { echo "Terraform directory not found: $TERRAFORM_DIR" >&2; exit 1; }
[[ -f "$FRONTEND_DIR/index.html" ]] || { echo "Frontend entry point not found: $FRONTEND_DIR/index.html" >&2; exit 1; }
[[ -f "$FRONTEND_DIR/config.template.js" ]] || { echo "Frontend configuration template not found: $FRONTEND_DIR/config.template.js" >&2; exit 1; }

terraform_output_raw() {
  terraform -chdir="$TERRAFORM_DIR" output -raw "$1"
}

API_ENDPOINT="$(terraform -chdir="$TERRAFORM_DIR" output -json primary_frontend_site | jq -er '.api_endpoint')"
USER_POOL_ID="$(terraform_output_raw cognito_user_pool_id)"
USER_POOL_CLIENT_ID="$(terraform_output_raw cognito_user_pool_client_id)"
FRONTEND_BUCKET="$(terraform_output_raw frontend_bucket_name)"
DISTRIBUTION_ID="$(terraform_output_raw cloudfront_distribution_id)"
FRONTEND_URL="$(terraform_output_raw frontend_url)"

for pair in \
  "API endpoint:$API_ENDPOINT" \
  "Cognito user pool ID:$USER_POOL_ID" \
  "Cognito client ID:$USER_POOL_CLIENT_ID" \
  "Frontend bucket:$FRONTEND_BUCKET" \
  "CloudFront distribution ID:$DISTRIBUTION_ID" \
  "Frontend URL:$FRONTEND_URL"; do
  name="${pair%%:*}"
  value="${pair#*:}"
  [[ -n "$value" && "$value" != "null" ]] || {
    echo "Terraform output is empty: $name" >&2
    exit 1
  }
done

STAGING_DIR="$(mktemp -d "${TMPDIR:-/tmp}/ai-resume-coach-frontend.XXXXXX")"
trap 'rm -rf "$STAGING_DIR"' EXIT

cp -a "$FRONTEND_DIR/." "$STAGING_DIR/"

cat > "$STAGING_DIR/config.js" <<EOF_CONFIG
// Generated by tools/operations/deploy_frontend.sh. Do not hard-code environment IDs here.
window.APP_CONFIG = {
  apiEndpoint: "${API_ENDPOINT}",
  cognitoUserPoolId: "${USER_POOL_ID}",
  cognitoUserPoolClientId: "${USER_POOL_CLIENT_ID}"
};
EOF_CONFIG

echo "Rendered frontend runtime configuration from Terraform outputs in a temporary deployment directory."
echo "Deploying $FRONTEND_DIR to s3://$FRONTEND_BUCKET/ ..."
aws s3 sync "$STAGING_DIR/" "s3://${FRONTEND_BUCKET}/" --delete \
  --exclude "config.template.js"

# Runtime configuration and HTML must be revalidated by browsers after each deployment.
aws s3 cp "$STAGING_DIR/config.js" "s3://${FRONTEND_BUCKET}/config.js" \
  --content-type "application/javascript" \
  --cache-control "no-store, no-cache, must-revalidate, max-age=0"

aws s3 cp "$STAGING_DIR/" "s3://${FRONTEND_BUCKET}/" \
  --recursive \
  --exclude "*" \
  --include "*.html" \
  --content-type "text/html" \
  --cache-control "no-cache, must-revalidate"

aws s3api head-object \
  --bucket "$FRONTEND_BUCKET" \
  --key index.html \
  >/dev/null

INVALIDATION_ID="$(
  aws cloudfront create-invalidation \
    --distribution-id "$DISTRIBUTION_ID" \
    --paths '/*' \
    --query 'Invalidation.Id' \
    --output text
)"

echo "Created CloudFront invalidation: $INVALIDATION_ID"

if [[ "$WAIT_FOR_INVALIDATION" == true ]]; then
  echo "Waiting for CloudFront invalidation to complete ..."
  aws cloudfront wait invalidation-completed \
    --distribution-id "$DISTRIBUTION_ID" \
    --id "$INVALIDATION_ID"
fi

if [[ "$HTTP_CHECK" == true ]]; then
  echo "Verifying $FRONTEND_URL ..."
  curl --fail --silent --show-error --location \
    --retry 6 --retry-delay 5 --retry-all-errors \
    --output /dev/null \
    "$FRONTEND_URL"
fi

echo "Frontend deployment complete."
echo "Frontend URL: $FRONTEND_URL"
echo "API endpoint: $API_ENDPOINT"
