#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
DOMAIN_NAME="${DOMAIN_NAME:-api.resume.michaelpopovich.com}"
HOSTED_ZONE_ID="${HOSTED_ZONE_ID:-Z074065915GNYUCPJUVGS}"
OUTPUT_TFVARS="${OUTPUT_TFVARS:-$ROOT_DIR/infra/global-api-routing.generated.tfvars}"
AWS_PROFILE_ARGS=()
[[ -n "${AWS_PROFILE:-}" ]] && AWS_PROFILE_ARGS=(--profile "$AWS_PROFILE")

fail() {
  printf 'FAILED: %s\n' "$*" >&2
  exit 1
}

for command in aws jq python3; do
  command -v "$command" >/dev/null || fail "$command is required"
done

certificate_arn() {
  local region="$1"
  local arn
  arn="$(aws acm list-certificates \
    "${AWS_PROFILE_ARGS[@]}" \
    --region "$region" \
    --certificate-statuses ISSUED PENDING_VALIDATION \
    --query "CertificateSummaryList[?DomainName=='${DOMAIN_NAME}'] | [0].CertificateArn" \
    --output text)"

  if [[ -z "$arn" || "$arn" == "None" ]]; then
    arn="$(aws acm request-certificate \
      "${AWS_PROFILE_ARGS[@]}" \
      --region "$region" \
      --domain-name "$DOMAIN_NAME" \
      --validation-method DNS \
      --idempotency-token "$(printf '%s-%s' "$DOMAIN_NAME" "$region" | sha256sum | cut -c1-32)" \
      --options CertificateTransparencyLoggingPreference=ENABLED \
      --query CertificateArn \
      --output text)"
    printf 'Requested certificate in %s: %s\n' "$region" "$arn" >&2
  else
    printf 'Reusing certificate in %s: %s\n' "$region" "$arn" >&2
  fi

  printf '%s' "$arn"
}

validation_record() {
  local region="$1"
  local arn="$2"
  local record=""

  for _ in $(seq 1 30); do
    record="$(aws acm describe-certificate \
      "${AWS_PROFILE_ARGS[@]}" \
      --region "$region" \
      --certificate-arn "$arn" \
      --query 'Certificate.DomainValidationOptions[0].ResourceRecord' \
      --output json)"
    if [[ "$record" != "null" ]] && jq -e '.Name and .Type and .Value' <<<"$record" >/dev/null; then
      printf '%s' "$record"
      return 0
    fi
    sleep 2
  done

  fail "ACM did not expose a DNS validation record for $arn"
}

east_arn="$(certificate_arn us-east-1)"
west_arn="$(certificate_arn us-west-2)"
east_record="$(validation_record us-east-1 "$east_arn")"
west_record="$(validation_record us-west-2 "$west_arn")"

if [[ "$(jq -cS . <<<"$east_record")" != "$(jq -cS . <<<"$west_record")" ]]; then
  fail "Regional ACM certificates returned different DNS validation records; validate them manually before continuing"
fi

record_name="$(jq -r '.Name' <<<"$east_record")"
record_type="$(jq -r '.Type' <<<"$east_record")"
record_value="$(jq -r '.Value' <<<"$east_record")"

change_batch="$(jq -n \
  --arg name "$record_name" \
  --arg type "$record_type" \
  --arg value "$record_value" \
  '{Comment:"MR-009D3C external ACM DNS validation",Changes:[{Action:"UPSERT",ResourceRecordSet:{Name:$name,Type:$type,TTL:300,ResourceRecords:[{Value:$value}]}}]}')"

aws route53 change-resource-record-sets \
  "${AWS_PROFILE_ARGS[@]}" \
  --hosted-zone-id "$HOSTED_ZONE_ID" \
  --change-batch "$change_batch" >/dev/null

printf 'Published ACM DNS validation record: %s\n' "$record_name"
printf 'Waiting for certificates to become ISSUED...\n'

aws acm wait certificate-validated "${AWS_PROFILE_ARGS[@]}" --region us-east-1 --certificate-arn "$east_arn"
aws acm wait certificate-validated "${AWS_PROFILE_ARGS[@]}" --region us-west-2 --certificate-arn "$west_arn"

cat >"$OUTPUT_TFVARS" <<EOF_TFVARS
# Generated by tools/multi_site/prepare_external_acm_certificates.sh
# Review before using with Terraform.
enable_global_api_routing        = true
enable_route53_api_health_checks = false

api_domain_name        = "$DOMAIN_NAME"
route53_public_zone_id = "$HOSTED_ZONE_ID"

east_api_certificate_arn = "$east_arn"
west_api_certificate_arn = "$west_arn"

site_routing_enabled = {
  east = true
  west = true
}
EOF_TFVARS

printf '\nExternal ACM certificates are ready.\n'
printf 'East: %s\n' "$east_arn"
printf 'West: %s\n' "$west_arn"
printf 'Generated Terraform variables: %s\n' "$OUTPUT_TFVARS"
